//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWOS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWOS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class BoardParser : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;Ship Boarding Stats&quot;;
        ///            }
        ///        }
        ///
        ///        // [01:19:55] You board on the &quot;Ocean Warrior&quot; as the captain.
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (!line.Contains(&quot;You board on the&quot;))
        ///            {
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoardParser {
            get {
                return ResourceManager.GetString("BoardParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class Create : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;Things you created.&quot;;
        ///            }
        ///        }
        ///
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (!line.Contains(&quot;You create&quot;))
        ///            {
        ///                return;
        ///            }
        ///
        ///            int start = line.IndexOf(&quot;t&quot;) + 3;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateParser {
            get {
                return ResourceManager.GetString("CreateParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class Dropped : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;SINGLE things you dropped&quot;;
        ///            }
        ///        }
        ///
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (!line.Contains(&quot;You drop a&quot;))
        ///            {
        ///                return;
        ///            }
        ///
        ///            int start = line.IndexOf(&quot;a&quot;) + 2;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string droppedParser {
            get {
                return ResourceManager.GetString("droppedParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class EnteringSettlements : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;Settlments you have entered.&quot;;
        ///            }
        ///        }
        ///
        ///        // [01:19:55] You board on the &quot;Ocean Warrior&quot; as the captain.
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (!line.Contains(&quot;You enter&quot;))
        ///            {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnteringParser {
            get {
                return ResourceManager.GetString("EnteringParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class LeavingSettlements : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;Settlments you have left.&quot;;
        ///            }
        ///        }
        ///
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (line.Contains(&quot;\&quot;&quot;))
        ///            {
        ///                return;
        ///            }
        ///            if (!line.Contains(&quot;You leave&quot;))
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeavingParser {
            get {
                return ResourceManager.GetString("LeavingParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class RepairingParser : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;Things you repaired&quot;;
        ///            }
        ///        }
        ///
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (!line.Contains(&quot;You repair&quot;))
        ///            {
        ///                return;
        ///            }
        ///
        ///            int start = line.IndexOf(&quot;h&quot;) + 2;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RepairingParser {
            get {
                return ResourceManager.GetString("RepairingParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using WParse;
        ///
        ///namespace EWOS.parsers
        ///{
        ///    public sealed class Titles : IParser
        ///    {
        ///        public string Name
        ///        {
        ///            get
        ///            {
        ///                return &quot;Titles you have achieved.&quot;;
        ///            }
        ///        }
        ///
        ///        public void Parse(string line, EventProxy proxy)
        ///        {
        ///            if (!line.Contains(&quot;You have just received the title&quot;))
        ///            {
        ///                return;
        ///            }
        ///
        ///            int start = line [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleParser {
            get {
                return ResourceManager.GetString("TitleParser", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wtfwowdelijpg {
            get {
                object obj = ResourceManager.GetObject("wtfwowdelijpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
